In [1]:
# Importar libreria Geopandas
import geopandas as gpd
import urllib.request
import xml.etree.ElementTree as ET

In [2]:
url = "https://www.ideandalucia.es/services/DERA_g12_servicios/wfs?service=wfs&request=getcapabilities"

gdf = gpd.read_file(
    url, 
    layer='DERA_g12_servicios:g12_01_CentroSalud', 
    engine="pyogrio", 
    encoding="utf-8"
)

URLError: <urlopen error [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder>

In [ ]:
gdf

,gml_id,id_dera,nombre,direccion,telefono,web,localidad,cod_mun,municipio,provincia,geometry
0,g12_01_CentroSalud.11213100016586,11213100016586,Los Pascuales,"TRAVESIA AVENIDA PUERTA (LA), 0",953439008,https://web.sas.junta-andalucia.es/servicioand...,Los Pascuales,23072,La Puerta de Segura,Jaén,MULTIPOINT ((515555.677 4248392.575))
1,g12_01_CentroSalud.11213100015684,11213100015684,Benamaurel,"CALLE CALDERON DE LA BARCA, 0",958869608,https://web.sas.junta-andalucia.es/servicioand...,Benamaurel,18029,Benamaurel,Granada,MULTIPOINT ((526681.975 4162248.628))
2,g12_01_CentroSalud.11213100015588,11213100015588,El Alcornocal,"CALLE CASTELAR (ALCORNOCAL), 5",600165925,https://web.sas.junta-andalucia.es/servicioand...,El Alcornocal,14029,Fuente Obejuna,Córdoba,MULTIPOINT ((295900.925 4228500.376))
3,g12_01_CentroSalud.11213100015997,11213100015997,El Molar,"AVENIDA ANDALUCIA (DE), 12",953105134,https://web.sas.junta-andalucia.es/servicioand...,El Molar,23028,Cazorla,Jaén,MULTIPOINT ((486809.08 4203642.59))
4,g12_01_CentroSalud.11213100015615,11213100015615,Almayate Alto,"CALLE FARMACEUTICO MORENO CHICA, 1",951289328,https://web.sas.junta-andalucia.es/servicioand...,Almayate Bajo,29094,Vélez-Málaga,Málaga,MULTIPOINT ((399131.892 4065564.99))
...,...,...,...,...,...,...,...,...,...,...,...
1511,g12_01_CentroSalud.11213100015779,11213100015779,Nechite,"CALLE PLAZA (DE LA), 5",600160078,https://web.sas.junta-andalucia.es/servicioand...,Nechite,18183,Válor,Granada,MULTIPOINT ((493637.813 4095204.083))
1512,g12_01_CentroSalud.11213100016177,11213100016177,San Sebastián de los Ballesteros,"CALLE NUEVAS POBLACIONES, 17",957307551,https://web.sas.junta-andalucia.es/servicioand...,San Sebastián de los Ballesteros,14059,San Sebastián de los Ballesteros,Córdoba,MULTIPOINT ((339056.788 4168831.519))
1513,g12_01_CentroSalud.11213100016716,11213100016716,Zagrilla,"PLAZA IGLESIA (DE LA) (ZAGRILLA ALTA), 10",957703753,https://web.sas.junta-andalucia.es/servicioand...,Zagrilla Alta,14055,Priego de Córdoba,Córdoba,MULTIPOINT ((390125.307 4149608.512))
1514,g12_01_CentroSalud.11213100016744,11213100016744,Terreros,"AVENIDA DEL MEDITERRANEO, 0",950474790,https://web.sas.junta-andalucia.es/servicioand...,San Juan de Terreros,04075,Pulpí,Almería,MULTIPOINT ((618126.951 4135749.67))
1515,g12_01_CentroSalud.11213100015352,11213100015352,Baena Dr. Ignacio Osuna Gómez,"CALLE SALVADOR MUÑOZ, 20",957699529,https://web.sas.junta-andalucia.es/servicioand...,Baena,14007,Baena,Córdoba,MULTIPOINT ((383391.944 4164377.662))

In [ ]:
# Borrrar columnas no necesarias
gdf = gdf.drop(columns=[ 'gml_id', 'id_dera', 'nombre', 'direccion', 'telefono', 'web', 'localidad', 'cod_mun',])

In [ ]:
gdf

,municipio,provincia,geometry
0,La Puerta de Segura,Jaén,MULTIPOINT ((515555.677 4248392.575))
1,Benamaurel,Granada,MULTIPOINT ((526681.975 4162248.628))
2,Fuente Obejuna,Córdoba,MULTIPOINT ((295900.925 4228500.376))
3,Cazorla,Jaén,MULTIPOINT ((486809.08 4203642.59))
4,Vélez-Málaga,Málaga,MULTIPOINT ((399131.892 4065564.99))
...,...,...,...
1511,Válor,Granada,MULTIPOINT ((493637.813 4095204.083))
1512,San Sebastián de los Ballesteros,Córdoba,MULTIPOINT ((339056.788 4168831.519))
1513,Priego de Córdoba,Córdoba,MULTIPOINT ((390125.307 4149608.512))
1514,Pulpí,Almería,MULTIPOINT ((618126.951 4135749.67))
1515,Baena,Córdoba,MULTIPOINT ((383391.944 4164377.662))

In [ ]:
url = "https://www.ideandalucia.es/services/DERA_g12_servicios/wfs?service=wfs&request=getcapabilities"

gdf = gpd.read_file(
    url, 
    layer='DERA_g12_servicios:g12_02_Hospital_CAE', 
    engine="pyogrio", 
    encoding="utf-8"
)

In [ ]:
gdf

,gml_id,id_dera,nombre,tipo,sistema_sa,direccion,web,localidad,cod_mun,municipio,provincia,geometry
0,g12_02_Hospital_CAE.11213200015138,11213200015138,HOSPITAL SAN JUAN DE DIOS DE SEVILLA,Hospital,Privado,"AVENIDA EDUARDO DATO, 42",https://web.sas.junta-andalucia.es/servicioand...,Sevilla,41091,Sevilla,Sevilla,MULTIPOINT ((237119.999 4141377.321))
1,g12_02_Hospital_CAE.11213200015261,11213200015261,HOSPITAL VIRGEN DE LA VICTORIA,Hospital,Público,"CALLE DEMOSTENES, 8",https://web.sas.junta-andalucia.es/servicioand...,Málaga,29067,Málaga,Málaga,MULTIPOINT ((368045.226 4064752.167))
2,g12_02_Hospital_CAE.11213200015123,11213200015123,HOSPITAL QUIRONSALUD MARBELLA,Hospital,Privado,"AVENIDA SEVERO OCHOA, 32",https://web.sas.junta-andalucia.es/servicioand...,Marbella,29069,Marbella,Málaga,MULTIPOINT ((332153.091 4042031.302))
3,g12_02_Hospital_CAE.11213200015267,11213200015267,Centro de Diagnóstico y Tratamiento del Hospit...,Centro de consultas externas,Público,"AVENIDA DEL EJERCITO ESPAÑOL, 12",https://web.sas.junta-andalucia.es/servicioand...,Jaén,23050,Jaén,Jaén,MULTIPOINT ((430149.8 4181144.98))
4,g12_02_Hospital_CAE.11213200015217,11213200015217,HOSPITAL DE ALTA RESOLUCION DE UTRERA,Hospital,Público,"AVENIDA BRIGADAS INTERNACIONALES, 0",https://web.sas.junta-andalucia.es/servicioand...,Utrera,41095,Utrera,Sevilla,MULTIPOINT ((252738.481 4118059.733))
...,...,...,...,...,...,...,...,...,...,...,...,...
178,g12_02_Hospital_CAE.11213200015121,11213200015121,CENTRO ASISTENCIAL HERMANAS HOSPITALARIAS DEL ...,Hospital,Privado,"CALLE SAN JUAN BOSCO, 41",https://web.sas.junta-andalucia.es/servicioand...,Málaga,29067,Málaga,Málaga,MULTIPOINT ((373019.869 4066247.253))
179,g12_02_Hospital_CAE.11213200015153,11213200015153,HOSPITAL SAN CARLOS DE SAN FERNANDO,Hospital,Público,"PASEO CAPITAN CONFORTO, S/N",https://web.sas.junta-andalucia.es/servicioand...,San Fernando,11031,San Fernando,Cádiz,MULTIPOINT ((213777.47 4041935.42))
180,g12_02_Hospital_CAE.11213200015230,11213200015230,HOSPITAL PUERTA DE ANDALUCIA,Hospital,Público,"CARRETERA J-12, 32",https://web.sas.junta-andalucia.es/servicioand...,Jaén,23050,Jaén,Jaén,MULTIPOINT ((431354.389 4183335.096))
181,g12_02_Hospital_CAE.11213200015277,11213200015277,Centro de consultas externas de Marchena,Centro de consultas externas,Público,"AVENIDA MAESTRO SANTOS RUANO, S/N",https://web.sas.junta-andalucia.es/servicioand...,Marchena,41060,Marchena,Sevilla,MULTIPOINT ((285478.33 4134582.987))
182,g12_02_Hospital_CAE.11213200015142,11213200015142,HOSPITAL INFANTA MARGARITA,Hospital,Público,"AVENIDA GONGORA, 9 - Hospital Infanta Margarita",https://web.sas.junta-andalucia.es/servicioand...,Cabra,14013,Cabra,Córdoba,MULTIPOINT ((373958.987 4147776.469))

In [ ]:
# Borrrar columnas no necesarias
gdf = gdf.drop(columns=[ 'gml_id', 'id_dera', 'web', 'cod_mun',])

In [ ]:
gdf

,nombre,tipo,sistema_sa,direccion,localidad,municipio,provincia,geometry
0,HOSPITAL SAN JUAN DE DIOS DE SEVILLA,Hospital,Privado,"AVENIDA EDUARDO DATO, 42",Sevilla,Sevilla,Sevilla,MULTIPOINT ((237119.999 4141377.321))
1,HOSPITAL VIRGEN DE LA VICTORIA,Hospital,Público,"CALLE DEMOSTENES, 8",Málaga,Málaga,Málaga,MULTIPOINT ((368045.226 4064752.167))
2,HOSPITAL QUIRONSALUD MARBELLA,Hospital,Privado,"AVENIDA SEVERO OCHOA, 32",Marbella,Marbella,Málaga,MULTIPOINT ((332153.091 4042031.302))
3,Centro de Diagnóstico y Tratamiento del Hospit...,Centro de consultas externas,Público,"AVENIDA DEL EJERCITO ESPAÑOL, 12",Jaén,Jaén,Jaén,MULTIPOINT ((430149.8 4181144.98))
4,HOSPITAL DE ALTA RESOLUCION DE UTRERA,Hospital,Público,"AVENIDA BRIGADAS INTERNACIONALES, 0",Utrera,Utrera,Sevilla,MULTIPOINT ((252738.481 4118059.733))
...,...,...,...,...,...,...,...,...
178,CENTRO ASISTENCIAL HERMANAS HOSPITALARIAS DEL ...,Hospital,Privado,"CALLE SAN JUAN BOSCO, 41",Málaga,Málaga,Málaga,MULTIPOINT ((373019.869 4066247.253))
179,HOSPITAL SAN CARLOS DE SAN FERNANDO,Hospital,Público,"PASEO CAPITAN CONFORTO, S/N",San Fernando,San Fernando,Cádiz,MULTIPOINT ((213777.47 4041935.42))
180,HOSPITAL PUERTA DE ANDALUCIA,Hospital,Público,"CARRETERA J-12, 32",Jaén,Jaén,Jaén,MULTIPOINT ((431354.389 4183335.096))
181,Centro de consultas externas de Marchena,Centro de consultas externas,Público,"AVENIDA MAESTRO SANTOS RUANO, S/N",Marchena,Marchena,Sevilla,MULTIPOINT ((285478.33 4134582.987))
182,HOSPITAL INFANTA MARGARITA,Hospital,Público,"AVENIDA GONGORA, 9 - Hospital Infanta Margarita",Cabra,Cabra,Córdoba,MULTIPOINT ((373958.987 4147776.469))

In [ ]:
url = "https://www.ideandalucia.es/services/DERA_g12_servicios/wfs?service=wfs&request=getcapabilities"

gdf = gpd.read_file(
    url, 
    layer='DERA_g12_servicios:g12_04_Farmacia', 
    engine="pyogrio", 
    encoding="utf-8"
)

In [ ]:
gdf

,gml_id,id_dera,nica,nombre,direccion,cod_mun,municipio,provincia,geometry
0,g12_04_Farmacia.11213400009499,11213400009499,40960,"LOPEZ GAGO, ILDEFONSO.- O.FARMACIA Nº 466",AVENIDA DIPUTACION 4,11015,Chiclana de la Frontera,Cádiz,MULTIPOINT ((216841.878 4034864.492))
1,g12_04_Farmacia.11213400009500,11213400009500,42779,"FARMACIA MARTINEZ PEREZ, MARIA DOLORES",AVENIDA DE LA CONSTITUCION 152,04066,Níjar,Almería,MULTIPOINT ((573773.821 4085075.644))
2,g12_04_Farmacia.11213400009501,11213400009501,41296,"GUTIERREZ ROMAN, MANUELA O.FARMACIA 437",AVENIDA DEL MAR 9,11007,Barbate,Cádiz,MULTIPOINT ((237597.593 4009418.347))
3,g12_04_Farmacia.11213400009502,11213400009502,42825,"CASTIILLO LOPEZ, INMACULADA",AVENIDA DE LAS PALMERAS 76 B,29025,Benalmádena,Málaga,MULTIPOINT ((362655.45 4050659.093))
4,g12_04_Farmacia.11213400009503,11213400009503,42826,"DÍEZ RODRIGUEZ, MONICA",AVENIDA DE LA CONSTITUCION 7,29069,Marbella,Málaga,MULTIPOINT ((321578.134 4039524.173))
...,...,...,...,...,...,...,...,...,...
3869,g12_04_Farmacia.11213400013368,11213400013368,20744,ISABEL AMPARO DOMINGUEZ DOMINGUEZ - OF. FARMAC...,CALLE LOS CUARTELES S/N,21025,Cortegana,Huelva,MULTIPOINT ((158228.905 4189354.233))
3870,g12_04_Farmacia.11213400013369,11213400013369,23605,Mª JOSE GARCIA MARQUEZ / VERONICA COLCHERO CER...,CALLE VALLE FRIO S/N,21021,Cartaya,Huelva,MULTIPOINT ((140047.224 4126173.047))
3871,g12_04_Farmacia.11213400013370,11213400013370,4928,"RODRIGUEZ SAMBLAS, NURIA",CALLE PILAR 6,23037,Génave,Jaén,MULTIPOINT ((523365.566 4253562.28))
3872,g12_04_Farmacia.11213400013371,11213400013371,4697,"MERIDA GUZMAN, NURIA",CALLE JACOB 8,29067,Málaga,Málaga,MULTIPOINT ((361794.504 4065906.489))
3873,g12_04_Farmacia.11213400013372,11213400013372,41717,"JIMENEZ ALCALA, FATIMA",CALLE DEL RIO 1,29085,Salares,Málaga,MULTIPOINT ((408690.025 4079160.623))

In [ ]:
# Borrrar columnas no necesarias
gdf = gdf.drop(columns=[ 'gml_id', 'id_dera', 'nica', 'cod_mun',])

In [ ]:
gdf

,nombre,direccion,municipio,provincia,geometry
0,"LOPEZ GAGO, ILDEFONSO.- O.FARMACIA Nº 466",AVENIDA DIPUTACION 4,Chiclana de la Frontera,Cádiz,MULTIPOINT ((216841.878 4034864.492))
1,"FARMACIA MARTINEZ PEREZ, MARIA DOLORES",AVENIDA DE LA CONSTITUCION 152,Níjar,Almería,MULTIPOINT ((573773.821 4085075.644))
2,"GUTIERREZ ROMAN, MANUELA O.FARMACIA 437",AVENIDA DEL MAR 9,Barbate,Cádiz,MULTIPOINT ((237597.593 4009418.347))
3,"CASTIILLO LOPEZ, INMACULADA",AVENIDA DE LAS PALMERAS 76 B,Benalmádena,Málaga,MULTIPOINT ((362655.45 4050659.093))
4,"DÍEZ RODRIGUEZ, MONICA",AVENIDA DE LA CONSTITUCION 7,Marbella,Málaga,MULTIPOINT ((321578.134 4039524.173))
...,...,...,...,...,...
3869,ISABEL AMPARO DOMINGUEZ DOMINGUEZ - OF. FARMAC...,CALLE LOS CUARTELES S/N,Cortegana,Huelva,MULTIPOINT ((158228.905 4189354.233))
3870,Mª JOSE GARCIA MARQUEZ / VERONICA COLCHERO CER...,CALLE VALLE FRIO S/N,Cartaya,Huelva,MULTIPOINT ((140047.224 4126173.047))
3871,"RODRIGUEZ SAMBLAS, NURIA",CALLE PILAR 6,Génave,Jaén,MULTIPOINT ((523365.566 4253562.28))
3872,"MERIDA GUZMAN, NURIA",CALLE JACOB 8,Málaga,Málaga,MULTIPOINT ((361794.504 4065906.489))
3873,"JIMENEZ ALCALA, FATIMA",CALLE DEL RIO 1,Salares,Málaga,MULTIPOINT ((408690.025 4079160.623))

In [ ]:
url = "https://www.ideandalucia.es/services/DERA_g7_sistema_urbano/wfs?service=wfs&request=getcapabilities"

gdf = gpd.read_file(
    url, 
    layer='DERA_g7_sistema_urbano:g07_06_ZonaVerde', 
    engine="pyogrio", 
    encoding="utf-8"
)

In [ ]:
gdf

,gml_id,id_dera,nombre,tipo,geometry
0,g07_06_ZonaVerde.10705500000001,10705500000001,Sin dato,Parque,"MULTIPOLYGON (((444906.196 4115298.675, 444995..."
1,g07_06_ZonaVerde.10705500000002,10705500000002,Sin dato,Jardín,"MULTIPOLYGON (((229132.476 4138664.121, 229137..."
2,g07_06_ZonaVerde.10705500000003,10705500000003,Sin dato,Parque,"MULTIPOLYGON (((414395.535 4173214.811, 414494..."
3,g07_06_ZonaVerde.10705500000004,10705500000004,Sin dato,Parque,"MULTIPOLYGON (((445008.359 4115219.725, 445069..."
4,g07_06_ZonaVerde.10705500000005,10705500000005,Sin dato,Parque,"MULTIPOLYGON (((414548.827 4173232.065, 414717..."

In [ ]:
# Borrrar columnas no necesarias
gdf = gdf.drop(columns=[ 'gml_id', 'id_dera', 'nombre',])

In [ ]:
gdf

               tipo                                           geometry
0            Parque  MULTIPOLYGON (((444906.196 4115298.675, 444995...
1            Jardín  MULTIPOLYGON (((229132.476 4138664.121, 229137...
2            Parque  MULTIPOLYGON (((414395.535 4173214.811, 414494...
3            Parque  MULTIPOLYGON (((445008.359 4115219.725, 445069...
4            Parque  MULTIPOLYGON (((414548.827 4173232.065, 414717...
...             ...                                                ...
9274         Parque  MULTIPOLYGON (((517305.832 4069616.61, 517363....
9275          Plaza  MULTIPOLYGON (((213075.664 4040931.035, 213102...
9276         Jardín  MULTIPOLYGON (((401307.45 4068603.149, 401318....
9277         Jardín  MULTIPOLYGON (((236545.432 4152612.1, 236561.1...
9278  Parque Canino  MULTIPOLYGON (((240333.571 4135917.435, 240309...

[9279 rows x 2 columns]

In [ ]:
# Borrrar columnas no necesarias
gdf = gdf.drop(columns=['id_dera', 'nombre',])

In [ ]:
url = "https://www.ideandalucia.es/services/DERA_g7_sistema_urbano/wfs?service=wfs&request=getcapabilities"

gdf = gpd.read_file(
    url, 
    layer='DERA_g7_sistema_urbano:g07_01_Poblaciones', 
    engine="pyogrio", 
    encoding="utf-8"
)

In [ ]:
# Borrrar columnas no necesarias
gdf = gdf.drop(columns=[ 'gml_id', 'id_dera', 'cod_sipob', 'pob_ine', 'nombre', 'nivel', 'cod_mun',])

In [ ]:
gdf

,municipio,provincia,geometry
0,Albox,Almería,"MULTIPOLYGON (((580059.063 4151157.388, 580079..."
1,Santiago-Pontones,Jaén,"MULTIPOLYGON (((542090.47 4229688.85, 542061.4..."
2,Benizalón,Almería,"MULTIPOLYGON (((568179.99 4116618.87, 568205.3..."
3,Senés,Almería,"MULTIPOLYGON (((559890.294 4115281.836, 559863..."
4,Fonelas,Granada,"MULTIPOLYGON (((483867.026 4140670.92, 483877...."
...,...,...,...
57614,Turrillas,Almería,"MULTIPOLYGON (((563243.558 4098886.188, 563279..."
57615,Albuñuelas,Granada,"MULTIPOLYGON (((444714.916 4087435.883, 444701..."
57616,Arenas del Rey,Granada,"MULTIPOLYGON (((422960.965 4096765.978, 422957..."
57617,Algeciras,Cádiz,"MULTIPOLYGON (((274482.51 3993995.8, 274487.45..."
57618,Santiago-Pontones,Jaén,"MULTIPOLYGON (((541920.758 4221401.133, 541917..."

In [ ]:
url = "https://www.ideandalucia.es/services/DERA_g7_sistema_urbano/wfs?service=wfs&request=getcapabilities"

gdf = gpd.read_file(
    url, 
    layer='DERA_g7_sistema_urbano:g07_06_ZonaVerde', 
    engine="pyogrio", 
    encoding="utf-8"
)

In [ ]:
gdf

,gml_id,id_dera,nombre,tipo,geometry
0,g07_06_ZonaVerde.10705500000001,10705500000001,Sin dato,Parque,"MULTIPOLYGON (((444906.196 4115298.675, 444995..."
1,g07_06_ZonaVerde.10705500000002,10705500000002,Sin dato,Jardín,"MULTIPOLYGON (((229132.476 4138664.121, 229137..."
2,g07_06_ZonaVerde.10705500000003,10705500000003,Sin dato,Parque,"MULTIPOLYGON (((414395.535 4173214.811, 414494..."
3,g07_06_ZonaVerde.10705500000004,10705500000004,Sin dato,Parque,"MULTIPOLYGON (((445008.359 4115219.725, 445069..."
4,g07_06_ZonaVerde.10705500000005,10705500000005,Sin dato,Parque,"MULTIPOLYGON (((414548.827 4173232.065, 414717..."
...,...,...,...,...,...
9274,g07_06_ZonaVerde.10705500009275,10705500009275,Sin dato,Parque,"MULTIPOLYGON (((517305.832 4069616.61, 517363...."
9275,g07_06_ZonaVerde.10705500009276,10705500009276,Sin dato,Plaza,"MULTIPOLYGON (((213075.664 4040931.035, 213102..."
9276,g07_06_ZonaVerde.10705500009277,10705500009277,Sin dato,Jardín,"MULTIPOLYGON (((401307.45 4068603.149, 401318...."
9277,g07_06_ZonaVerde.10705500009278,10705500009278,Sin dato,Jardín,"MULTIPOLYGON (((236545.432 4152612.1, 236561.1..."
9278,g07_06_ZonaVerde.10705500009279,10705500009279,Sin dato,Parque Canino,"MULTIPOLYGON (((240333.571 4135917.435, 240309..."

In [ ]:
# Borrrar columnas no necesarias
gdf = gdf.drop(columns=[ 'gml_id', 'id_dera', 'nombre',])

In [ ]:
gdf

               tipo                                           geometry
0            Parque  MULTIPOLYGON (((444906.196 4115298.675, 444995...
1            Jardín  MULTIPOLYGON (((229132.476 4138664.121, 229137...
2            Parque  MULTIPOLYGON (((414395.535 4173214.811, 414494...
3            Parque  MULTIPOLYGON (((445008.359 4115219.725, 445069...
4            Parque  MULTIPOLYGON (((414548.827 4173232.065, 414717...
...             ...                                                ...
9274         Parque  MULTIPOLYGON (((517305.832 4069616.61, 517363....
9275          Plaza  MULTIPOLYGON (((213075.664 4040931.035, 213102...
9276         Jardín  MULTIPOLYGON (((401307.45 4068603.149, 401318....
9277         Jardín  MULTIPOLYGON (((236545.432 4152612.1, 236561.1...
9278  Parque Canino  MULTIPOLYGON (((240333.571 4135917.435, 240309...

[9279 rows x 2 columns]